### ISSUE TITLE
Ignore kmd directory permissions on Windows

### ISSUE THREAD

**Issue by hernandp** [algorand/go-algorand#1907]
Hi, I'm from the Rand Labs team and we have released an installer package for Windows, as you may know. 
The problem that we are getting is that in Windows permissions are not really mapped to UNIX/linux kind of permissions or viceversa; for directories it will always return 0777. That makes impossible to run goal kmd and related commands (signing, sending transactions, etc) in Windows builds.

The exact error stack is:
```
time="2021-02-11T19:06:21.845227 -0300" level=error msg="[Stack] goroutine 1 [running]:\nruntime/debug.Stack(0xc000216070, 0xc000218000, 0xc0000f0850)\n\truntime/debug/stack.go:24 +0xa5\ngithub.com/algorand/go-algorand/logging.logger.Errorf(0xc000216070, 0xc000218000, 0x14410cf, 0x42, 0xc00041d140, 0x3, 0x3)\n\tgithub.com/algorand/go-algorand/logging/log.go:229 +0x54\ngithub.com/algorand/go-algorand/nodecontrol.(*KMDController).StartKMD(0xc00031d070, 0x3c, 0x0, 0xc00044cf42, 0x33)\n\tgithub.com/algorand/go-algorand/nodecontrol/kmdControl.go:204 +0xc69\ngithub.com/algorand/go-algorand/libgoal.(*Client).getKMDClient(0xc00031d010, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/algorand/go-algorand/libgoal/libgoal.go:240 +0x94\ngithub.com/algorand/go-algorand/libgoal.(*Client).ensureKmdClient(...)\n\tgithub.com/algorand/go-algorand/libgoal/libgoal.go:185\ngithub.com/algorand/go-algorand/libgoal.(*Client).init(0xc00031d010, 0xc00002c390, 0x24, 0xc00008b9e0, 0x2d, 0xc00008ba40, 0x2f, 0xc00008bb30, 0x21, 0x3, ...)\n\tgithub.com/algorand/go-algorand/libgoal/libgoal.go:163 +0x2a5\ngithub.com/algorand/go-algorand/libgoal.MakeClientFromConfig(0xc00002c390, 0x24, 0xc00008b9e0, 0x2d, 0xc00008ba40, 0x2f, 0xc00008bb30, 0x21, 0x3, 0xc00008bb60, ...)\n\tgithub.com/algorand/go-algorand/libgoal/libgoal.go:128 +0xad\nmain.ensureGoalClient(0xc00002c390, 0x24, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/algorand/go-algorand/cmd/goal/commands.go:380 +0x18b\nmain.ensureFullClient(...)\n\tgithub.com/algorand/go-algorand/cmd/goal/commands.go:371\nmain.glob..func43(0x115fea0, 0xc00009ec80, 0x0, 0x5)\n\tgithub.com/algorand/go-algorand/cmd/goal/clerk.go:353 +0x3fa\ngithub.com/spf13/cobra.(*Command).execute(0x115fea0, 0xc00009ec30, 0x5, 0x5, 0x115fea0, 0xc00009ec30)\n\tgithub.com/spf13/cobra@v0.0.3/command.go:766 +0x2c2\ngithub.com/spf13/cobra.(*Command).ExecuteC(0x115e220, 0x0, 0x1449b9a, 0xc3)\n\tgithub.com/spf13/cobra@v0.0.3/command.go:852 +0x308\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\tgithub.com/spf13/cobra@v0.0.3/command.go:800\nmain.main()\n\tgithub.com/algorand/go-algorand/cmd/goal/commands.go:155 +0x9d\n" file=kmdControl.go function="github.com/algorand/go-algorand/nodecontrol.(*KMDController).StartKMD" line=204
time="2021-02-11T19:06:21.848238 -0300" level=error msg="C:\\ProgramData\\Algorand\\data\\testnet\\kmd-v0.5: kmd data dir exists but is too permissive (777), change to (700)" file=kmdControl.go function="github.com/algorand/go-algorand/nodecontrol.(*KMDController).StartKMD" line=204
Cannot contact Algorand node: kmd data dir not secure
```

Reviewing the node code it would be enough -when running under Windows - to skip the permissions of 0777 for the kmd directory in kmdControl.go line 203:
```
	if (dataDirStat.Mode() & 0077) != 0 {
			logging.Base().Errorf("%s: kmd data dir exists but is too permissive (%o), change to (%o)", kc.kmdDataDir, dataDirStat.Mode()&0777, DefaultKMDDataDirPerms)
			return false, errors.New("kmd data dir not secure")
		}
``` 

Keep in mind that in our installer we will enforce the data directory and children to be secured with proper ACLs.

According to the conventions of code, I guess that a file with behavior for Windows systems is required, something along the lines of kmdControl_windows.go.  I'm right?

Thanks in advance.

**Comment by tsachiherman** [comment]
Yes, I think that moving the logic to be unix specific is a good idea.
My suggestion is that you would create the `kmdControl_windows.go` and `kmdControl_unix.go` as suggested and add a method checkKMDDirectoryPermissions(..) with a separate implementation for windows/unix.
For unix, we should retain the existing logic.
For windows, I'm not sure (yet) what the proper way to do it, since we don't officially support windows.

**Comment by ian-algorand** [comment]
@hernandp i'm being told that the fix that you've proposed (https://github.com/algorand/go-algorand/commit/4135b816a196f1c8338ae617212ed40684a2960e) has been merged. Can you please close this issue if so?

**Comment by hernandp** [comment]
Fixed. Closing this,  thanks guys.
