### ISSUE TITLE
Msgpack bytestring/text encoding

### ISSUE THREAD

**Issue by georgeee** [algorand/go-algorand#1968]
### Subject of the issue

Hi! I attached msgpack encoding of block `9414973` from testnet (retrieved via [url](https://api.betanet.algoexplorer.io/v2/blocks/9414973?format=msgpack)). It doesn't meet [msgpack specification](https://github.com/msgpack/msgpack/blob/master/spec.md#str-format-family).

It encodes some address field of a transaction as string. However specification of messagepack clearly says that this encoding is for UTF-8 strings, not bytestring.

### Your environment

N/A
[file.zip](https://github.com/algorand/go-algorand/files/6135149/file.zip)

### Steps to reproduce

Try parsing attached file with some msgpack parser (e.g. this Haskell [library](https://github.com/TokTok/hs-msgpack-binary)).

### Expected behaviour

File is parsed.

### Actual behaviour

File is not parsed due to wrongly encoded bytestring field.

**Comment by georgeee** [comment]
Here is the source of the bug: https://github.com/algorand/go-algorand/blob/3fce706479573bcee6c5cadd5465cd32e7175328/data/basics/teal.go#L46

**Comment by ian-algorand** [comment]
Need to do some initial investigation on this before we jump into implementing a solution.

**Comment by kirelagin** [comment]
Let me chime in to, hopefully, clarify what is happening, at least the way I understand it.

In Go there are two, essentially, equivalent types: `string` and `[]byte` – the only difference between them is that the former is immutable. That is in contrast to other modern programming languages where “string” means a sequence of Unicode codepoints rather than bytes.

I don’t have a lot of experience with Go, but, I think, there is no universal agreement that e.g. `string` should only ever be used for valid UTF-8 encodings, although that kind of seems to be the intent of the creators of the language.

Now, in MessagePack, there are two types: `String` (and its corresponding format `str`) and `Binary` (and its corresponding format `bin`). In line with the interpretation of higher-level languages, the MessagePack specification _requires_ `String` to be a valid UTF-8 encoding of a Unicode string.

The final component of the issue is the `go-codec` library, [which, by default, maps][codec-map] Go `string` to MessagePack `str` (and Go `[]byte` to MessagePack `bin`). The first part of this mapping is incorrect in general, since in Go `string` can contain arbitrary bytes, but in MessagePack `str` cannot.

So, there are two ways to fix this situation:

1. Make sure that all structs use `[]byte` instead of `string` at all places where arbitrary bytes, rather than correct UTF-8-encoded codepoints, can be found.
2. Keep using `string`, but [set `StringToRaw = true`][flag] in the codec configuration (however, if there are places in the protocol where genuine strings are used, they will be serialised to `bin` now; not a big deal and, I believe, the only reason to prefer `str` over `bin` where possible is that its serialisation is more compact).

[flag]: https://github.com/ugorji/go/blob/76603559030f291b11839a54bae70045f07d583f/codec/encode.go#L139-L150

Either way, current serialisation procedure is, unfortunately, not compliant with the specification and will definitely cause problems for standard-compliant decoders in languages that have a “real” string type. E.g. the transaction linked in the first comment cannot be decoded by `py-algorand-sdk`, since Python’s `msgpack` will fail to decode arbitrary bytes as a string:

```text
>>> msgpack.unpackb(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kirelagin/proj/serokell/py-algorand-sdk/venv/lib/python3.8/site-packages/msgpack/fallback.py", line 127, in unpackb
    unpacker.feed(packed)
  File "/home/kirelagin/proj/serokell/py-algorand-sdk/venv/lib/python3.8/site-packages/msgpack/fallback.py", line 343, in feed
    view = _get_data_from_buffer(next_bytes)
  File "/home/kirelagin/proj/serokell/py-algorand-sdk/venv/lib/python3.8/site-packages/msgpack/fallback.py", line 108, in _get_data_from_buffer
    view = memoryview(obj)
TypeError: memoryview: a bytes-like object is required, not 'str'
```

And either way, fixing this means breaking the wire format compatibility for Algorand.

[codec-map]: https://github.com/ugorji/go/blob/76603559030f291b11839a54bae70045f07d583f/codec/msgpack.go#L357-L387

**Comment by kirelagin** [comment]
(This might actually be worth filing an issue in `go-crypt` to change `StringToRaw ` to `true` by default, because this way people will, at least, be aware of the caveat and it will not produce potentially incorrect encodings with default settings.)
