### ISSUE TITLE
algod Crashes on ARM32 With panic: unaligned 64-bit atomic operation 

### ISSUE THREAD

**Issue by riceke** [algorand/go-algorand#1992]
### Subject of the issue

Since a day ago or so (probably after the new consensus upgrade was accepted by the network?) my algod process started crashing with: panic: unaligned 64-bit atomic operation 

### Your environment

Hardware: ASUS Tinker Board
OS: Armbian 21.02.3 based on Ubuntu Focal
Algo Version: 2.4.102919.dev [master] (commit #cde5b217)

Stack Trace:

panic: unaligned 64-bit atomic operation

goroutine 266 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x2520ed4, 0x1, 0x0, 0x6475340, 0x2a3c0ef)
        runtime/internal/atomic/asm_arm.s:233 +0x14
github.com/algorand/go-algorand/network.(*wsPeer).getRequestNonce(0x2520dc0, 0xa, 0x0, 0x692a89f)
        github.com/algorand/go-algorand/network/wsPeer.go:732 +0x54
github.com/algorand/go-algorand/network.(*wsPeer).Request(0x2520dc0, 0xf5b9f4, 0x6913f00, 0xd48d7b, 0x2, 0x25c41b0, 0x2, 0x2, 0x0, 0x0, ...)
        github.com/algorand/go-algorand/network/wsPeer.go:740 +0x4c
github.com/algorand/go-algorand/catchup.(*wsFetcherClient).requestBlock(0x692a860, 0xf5b9f4, 0x6913f00, 0x1, 0x0, 0x6913f00, 0x6433798, 0x1, 0x44, 0x1c)
        github.com/algorand/go-algorand/catchup/universalFetcher.go:164 +0x1e8
github.com/algorand/go-algorand/catchup.(*wsFetcherClient).getBlockBytes(0x692a860, 0xf5b9b4, 0x692a820, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/algorand/go-algorand/catchup/universalFetcher.go:138 +0x118
github.com/algorand/go-algorand/catchup.(*universalBlockFetcher).fetchBlock(0x5266000, 0xf5b9b4, 0x692a820, 0x1, 0x0, 0xd21448, 0x2520dc0, 0x2, 0x1, 0x1, ...)
        github.com/algorand/go-algorand/catchup/universalFetcher.go:68 +0xd4
github.com/algorand/go-algorand/catchup.(*Service).innerFetch(0x25dfc00, 0x1, 0x0, 0xd21448, 0x2520dc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/algorand/go-algorand/catchup/service.go:167 +0x1e0
github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite(0x25dfc00, 0x1, 0x0, 0x672e640, 0x672e600, 0x2580240, 0x6267a14)
        github.com/algorand/go-algorand/catchup/service.go:197 +0xc4
github.com/algorand/go-algorand/catchup.(*Service).pipelineCallback.func1(0x6741400, 0x24f0fd0)
        github.com/algorand/go-algorand/catchup/service.go:314 +0x58
github.com/algorand/go-algorand/catchup.(*Service).pipelinedFetch.func2(0x67442b0, 0x6741400, 0x59a00c0)
        github.com/algorand/go-algorand/catchup/service.go:358 +0x5c
created by github.com/algorand/go-algorand/catchup.(*Service).pipelinedFetch
        github.com/algorand/go-algorand/catchup/service.go:355 +0x190

### Steps to reproduce

1. Get latest code from master and build.
2. Launch node and wait for it to crash.

It does not matter if I try to run from where my local copy of mainnet data was when the crashing started (possibly because of consensus upgrade?) or if I start off with synching everything from scratch. The result is the same, i.e. node crashing.

### Expected behaviour

Node should stay up and running.

### Actual behaviour

Node crashes.

**Comment by riceke** [comment]
So, I think I managed to "fix" this issue.

By moving the 'requestNonce' variable, from its initial position in the 'wsPeer' struct, to immediately after 'lastPacketTime', at the beginning of the struct, it seems that it became 64 bit aligned and the problem went away.

After rebuilding, my node now stays up and is running properly again.

Thanks!
