### ISSUE TITLE
algod panics on startup

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#2101]
### Subject of the issue

Node panics upon startup on ARM

### Your environment

version 2.5.4

### Steps to reproduce

Start algod

### Expected behaviour

Starts normally

### Actual behaviour

crashes.

### Details:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb559d460]

goroutine 1 [running]:
runtime/internal/atomic.goLoad64(0x850712ac, 0x852618e4, 0x85071201)
runtime/internal/atomic/atomic_arm.go:131 +0x1c
github.com/algorand/go-algorand/crypto/merklearray.(*workerState).nextWorker(0x85071290, 0x8526190c)
github.com/algorand/go-algorand/crypto/merklearray/worker.go:90 +0x44
github.com/algorand/go-algorand/crypto/merklearray.Build(0xb680a3f8, 0x8976c580, 0x40, 0x0, 0x5f767a0)
github.com/algorand/go-algorand/crypto/merklearray/merkle.go:75 +0x158
github.com/algorand/go-algorand/data/bookkeeping.Block.TxnMerkleTree(...)
github.com/algorand/go-algorand/data/bookkeeping/txn_merkle.go:34
github.com/algorand/go-algorand/data/bookkeeping.Block.paysetCommit(0xcc9e54, 0x0, 0x90e60256, 0xa8db0b53, 0xc9d9a9a6, 0x226ca5aa, 0xca258862, 0xe06b8443, 0xd5cf287c, 0xdf24a63c, …)
github.com/algorand/go-algorand/data/bookkeeping/block.go:500 +0x154
github.com/algorand/go-algorand/data/bookkeeping.Block.PaysetCommit(0xcc9e54, 0x0, 0x90e60256, 0xa8db0b53, 0xc9d9a9a6, 0x226ca5aa, 0xca258862, 0xe06b8443, 0xd5cf287c, 0xdf24a63c, …)
github.com/algorand/go-algorand/data/bookkeeping/block.go:492 +0xac
github.com/algorand/go-algorand/data/bookkeeping.MakeBlock(0xcc9e53, 0x0, 0xadd3ee81, 0x2ee71957, 0xb7eaef9, 0xe59ab55c, 0x3744ff48, 0xc8fdfd18, 0xe1428d9a, 0xf42fe4e2, …)
github.com/algorand/go-algorand/data/bookkeeping/block.go:477 +0x3d0
github.com/algorand/go-algorand/data/pools.(*TransactionPool).recomputeBlockEvaluator(0x851be6c0, 0x852645d4, 0x0, 0x85196540, 0x59, 0x0, 0x0)
github.com/algorand/go-algorand/data/pools/transactionPool.go:666 +0x338
github.com/algorand/go-algorand/data/pools.MakeTransactionPool(0x8582a000, 0x0, 0x0, 0x4, 0x0, 0x0, 0xf8475800, 0xd, 0x0, 0x0, …)
github.com/algorand/go-algorand/data/pools/transactionPool.go:112 +0x250
github.com/algorand/go-algorand/node.MakeFull(0xb6818768, 0x850107d0, 0x8502b060, 0x12, 0x0, 0x0, 0x4, 0x0, 0x0, 0xf8475800, …)
github.com/algorand/go-algorand/node/node.go:208 +0xbe8
github.com/algorand/go-algorand/daemon/algod.(*Server).Initialize(0x85265db4, 0x0, 0x0, 0x4, 0x0, 0x0, 0xf8475800, 0xd, 0x0, 0x0, …)
github.com/algorand/go-algorand/daemon/algod/server.go:127 +0x5b4
main.main()
github.com/algorand/go-algorand/cmd/algod/main.go:292 +0xd8c
```

**Comment by riceke** [comment]
Hello!

I am also seeing this issue on ARM32.

Moving the 'maxidx' and 'nextidx' variables to the beginning of the 'workerState' struct in 'crypto/merklearray/worker.go' seems to fix the issue.

Thanks!

**Comment by Ansuz4u** [comment]
> Hello!
> 
> I am also seeing this issue on ARM32.
> 
> Moving the 'maxidx' and 'nextidx' variables to the beginning of the 'workerState' struct in 'crypto/merklearray/worker.go' seems to fix the issue.
> 
> Thanks!

Where do I find this.  I’m new and I’m the original source of this please share how you fixed this. Can you provide the proper commands with images for me? Or will there be an update to fix this issue?

**Comment by tsachiherman** [comment]
I have applied the mentioned fix, and will try to promote it to the next coming release ( it might be 2.5.6, but I don't know ).

**Comment by Ansuz4u** [comment]
Thank you
