### ISSUE TITLE
TestOnSwitchToUnSupportedProtocol randomly causes a memory violation

### ISSUE THREAD

**Issue by algonautshant** [algorand/go-algorand#2200]
## Summary

When running TestOnSwitchToUnSupportedProtocol many times, occasionally, the following runtime error is observed

```
2021/05/25 19:57:11 http: panic serving [::1]:59524: runtime error: invalid memory address or nil pointer dereference
goroutine 434 [running]:
net/http.(*conn).serve.func1(0xc000128000)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x4d94a00, 0x567be40)
	/usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/algorand/go-algorand/ledger.(*blockQueue).checkEntry(0x0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	go/src/github.com/algorand/go-algorand/ledger/blockqueue.go:215 +0x5f
github.com/algorand/go-algorand/ledger.(*blockQueue).getEncodedBlockCert(0x0, 0x3, 0x508a670, 0x100000001, 0x203000, 0xc000b7f8f8, 0x4019bfd, 0x4f179ed, 0x4eec867, 0x9)
	go/src/github.com/algorand/go-algorand/ledger/blockqueue.go:295 +0x87
github.com/algorand/go-algorand/ledger.(*Ledger).EncodedBlockCert(...)
	go/src/github.com/algorand/go-algorand/ledger/ledger.go:536
github.com/algorand/go-algorand/rpcs.RawBlockBytes(0xc0001bbc80, 0x3, 0x24, 0x40, 0x3, 0x0, 0x0)
	go/src/github.com/algorand/go-algorand/rpcs/blockService.go:383 +0x57
github.com/algorand/go-algorand/rpcs.(*BlockService).ServeHTTP(0xc000114800, 0x50c0200, 0xc000348000, 0xc000350100)
	go/src/github.com/algorand/go-algorand/rpcs/blockService.go:201 +0x592
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000126a10, 0x50c0200, 0xc000348000, 0xc000b49200)
	go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162 +0x106
net/http.serverHandler.ServeHTTP(0xc000b3ec70, 0x50c0200, 0xc000348000, 0xc000b49200)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000128000, 0x50c4540, 0xc000042f40)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
PASS

```

## Scope/Requirements

Investigate and fix the cause of the runtime error.
## Urgency/Relative Priority

This is urgent, as every memory errors.

**Comment by algonautshant** [comment]
This happens when the blockService has a request for a block, while the ledger is closed. 
This never happens in the context of the node because the node does not close the ledger. 
The cases where the ledger is closed are not in the context of the node, where a blockService may run. 

This is not harmful, and in addition, the test does not fail when this happens.

**Comment by algonautshant** [comment]
Fixing this will require unnecessary locks in the ledger operation.

**Comment by algonautshant** [comment]
Closing this bug since it is never happens in production code. 
Fixing this for the test will require unnecessary locks and checks. 
This has no impact on test. The test still passes, since the violation happens in the testing tool running in a separate process.
