### ISSUE TITLE
Broken test: TestPartitionRecoveryStaggerRestart

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2382]
## Description
Travis Test Errors Reference Spreadsheet for details on cases where this test has failed: https://docs.google.com/spreadsheets/d/1apjaNvZodnTSIdZaQlpMaqf0nzbKgSYdIWHqvmINHS8/edit#gid=0

### Example Failure
Time: Thu 7/15/2021
Build: https://app.travis-ci.com/github/algorand/go-algorand/jobs/524585138#L2872
Travis Test: Ubuntu AMD64 Integration Test, MacOS AMD64 Integration Test
Package: test/e2e-go/features/partitionRecovery
Test: TestPartitionRecoveryStaggerRestart

Ubuntu:
```
algod(11820) : panic: (*logrus.Entry) (0x1b4be00,0xc003944b60) [recovered]
algod(11820) : 	panic: (*logrus.Entry) (0x1b4be00,0xc003944b60)
algod(11820) : goroutine 16827 [running]:
algod(11820) : github.com/[secure]/go-[secure]/logging.logger.Panic.func1(0xc0001407e0, 0xc0000be558)
algod(11820) : 	github.com/[secure]/go-[secure]/logging/log.go:252 +0xd5
algod(11820) : panic(0x1b4be00, 0xc003944b60)
algod(11820) : 	runtime/panic.go:975 +0x3e3
algod(11820) : github.com/sirupsen/logrus.Entry.log(0xc000140770, 0xc0039606f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
algod(11820) : 	github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x56a
algod(11820) : github.com/sirupsen/logrus.(*Entry).Log(0xc003944af0, 0x0, 0xc0035e3d90, 0x1, 0x1)
algod(11820) : 	github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0x15f
algod(11820) : github.com/sirupsen/logrus.(*Entry).Panic(0xc003944af0, 0xc0035e3d90, 0x1, 0x1)
algod(11820) : 	github.com/sirupsen/logrus@v1.4.2/entry.go:306 +0x63
algod(11820) : github.com/[secure]/go-[secure]/logging.logger.Panic(0xc0001407e0, 0xc0000be558, 0xc0035e3d90, 0x1, 0x1)
algod(11820) : 	github.com/[secure]/go-[secure]/logging/log.go:256 +0x1ca
algod(11820) : github.com/[secure]/go-[secure]/daemon/algod.(*deadlockLogger).Panic(...)
algod(11820) : 	github.com/[secure]/go-[secure]/daemon/algod/deadlockLogger.go:41
algod(11820) : github.com/[secure]/go-[secure]/daemon/algod.(*deadlockLogger).onPotentialDeadlock.func1.1(0xc00007bc00, 0xc003913000, 0xf20)
algod(11820) : 	github.com/[secure]/go-[secure]/daemon/algod/deadlockLogger.go:85 +0xf7
algod(11820) : created by github.com/[secure]/go-[secure]/daemon/algod.(*deadlockLogger).onPotentialDeadlock.func1
algod(11820) : 	github.com/[secure]/go-[secure]/daemon/algod/deadlockLogger.go:83 +0x204
=== FAIL: test/e2e-go/features/partitionRecovery TestPartitionRecoveryStaggerRestart (unknown)
DONE 124 tests, 5 skipped, 5 failures in 1789.427s
Makefile:247: recipe for target 'integration' failed
make: *** [integration] Error 1
/home/travis/build/[secure]/go-[secure]/scripts/travis/travis_wait.sh: line 34: 31254 Terminated              travis_jigger $! $timeout $cmd
The command "/home/travis/build/[secure]/go-[secure]/scripts/travis/travis_wait.sh 90 /home/travis/build/[secure]/go-[secure]/scripts/travis/test.sh" failed. Retrying, 2 of 3.
```
Mac: https://app.travis-ci.com/github/algorand/go-algorand/jobs/524585141#L838
```
=== FAIL: test/e2e-go/features/partitionRecovery TestPartitionRecoveryStaggerRestart (75.54s)
    fixture.go:105: 
        	Error Trace:	partitionRecovery_test.go:151
        	            				partitionRecovery_test.go:113
        	Error:      	Not equal: 
        	            	expected: 0x3
        	            	actual  : 0x4
        	Test:       	TestPartitionRecoveryStaggerRestart
        	Messages:   	We should not have made progress since stopping the first node
algod(48774) : Exiting on terminated
algod(48771) : Exiting on terminated
algod(48750) : Exiting on terminated
```

**Comment by yaovi-a** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Algorand-Main-Workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/2382?planning-poker) with ZenHub @algobolson @algonautshant @AlgoStephenAkiki @nicholasguoalgorand @tolikzinovyev @tsachizehub @winder
