### ISSUE TITLE
`TestAgreementSynchronous` style agreement tests succeed locally but fail on Travis for 8, 9, 10 nodes

### ISSUE THREAD

**Issue by Vervious** [algorand/go-algorand#283]
In `agreement/service_test.go` there are a series of very simple

`TestAgreementSynchronousN` tests, where N is some number of players. They do a very basic simulation of a couple of rounds. 

They pass fine locally even with many samples, but for N >= 8 they appear to fail consistently on Travis. This is probably a problem with the testing infrastructure but should definitely be investigated.

**Comment by Vervious** [comment]
(also blocks #226 - asynch ensure digest - but unclear if we want to table that for a while)

**Comment by dncohen** [comment]
Fails on my local (fedora 30) environment.  Any ideas?

(I'm new to algorand and this is my first `make test`.)

```
--- FAIL: TestAgreementSynchronous10 (7.12s)                                                                                 
panic: timed out waiting for quiet... [recovered]                                                                            
        panic: timed out waiting for quiet... [recovered]                                                                    
        panic: timed out waiting for quiet...                                                                                
                                                                                                                             
goroutine 78830 [running]:                                                                                                   
testing.tRunner.func1(0xc0015e2800)                                                                                          
        /opt/go1.13.x/src/testing/testing.go:874 +0x69f                                                                      
panic(0x125f800, 0x1829ed0)                                                                                                  
        /opt/go1.13.x/src/runtime/panic.go:679 +0x1b2                                                                        
github.com/algorand/go-algorand/agreement.setupAgreement.func1()                                                             
        /home/user/gopath/algorand/src/github.com/algorand/go-algorand/agreement/service_test.go:769 +0x2e4                  
panic(0x125f800, 0x1829ed0)                                                                                                  
        /opt/go1.13.x/src/runtime/panic.go:679 +0x1b2                                                                        
github.com/algorand/go-algorand/agreement.(*activityMonitor).waitForQuiet(0xc002447440)                                      
        /home/user/gopath/algorand/src/github.com/algorand/go-algorand/agreement/service_test.go:557 +0x352                  
github.com/algorand/go-algorand/agreement.triggerGlobalTimeout(0xee6b2800, 0xc00021cb40, 0xa, 0xa, 0xc002447440)             
        /home/user/gopath/algorand/src/github.com/algorand/go-algorand/agreement/service_test.go:832 +0x160                  
github.com/algorand/go-algorand/agreement.runRound(0xc00021cb40, 0xa, 0xa, 0xc002447440, 0x1, 0x1862240)                     
        /home/user/gopath/algorand/src/github.com/algorand/go-algorand/agreement/service_test.go:836 +0x77                   
github.com/algorand/go-algorand/agreement.simulateAgreementWithLedgerFactory(0xc0015e2800, 0xa, 0x5, 0x0, 0x143e650)         
        /home/user/gopath/algorand/src/github.com/algorand/go-algorand/agreement/service_test.go:874 +0x2b4                  
github.com/algorand/go-algorand/agreement.simulateAgreement(...)                                                             
        /home/user/gopath/algorand/src/github.com/algorand/go-algorand/agreement/service_test.go:858                         
github.com/algorand/go-algorand/agreement.TestAgreementSynchronous10(0xc0015e2800)                                           
        /home/user/gopath/algorand/src/github.com/algorand/go-algorand/agreement/service_test.go:929 +0xee                   
testing.tRunner(0xc0015e2800, 0x143e1b8)                                                                                     
        /opt/go1.13.x/src/testing/testing.go:909 +0x19a                                                                      
created by testing.(*T).Run                                                                                                  
        /opt/go1.13.x/src/testing/testing.go:960 +0x652                                                                      
FAIL    github.com/algorand/go-algorand/agreement       38.137s                                                              
```

**Comment by derbear** [comment]
These tests are probably racy. It may be worth disabling them temporarily and later getting to the bottom of them...

@dncohen If you'd like, can you attach the `.cdv` files that result from the failed test? Those files hold the "transcript" of the agreement protocol running and can be very helpful for debugging. Thanks!

**Comment by dncohen** [comment]
There are quite a few .cdv files.  Several named "./agreement/TestAgreementSynchronous10-*.cdv"

Attaching in a format that github is OK with.

[issue-283.tar.gz](https://github.com/algorand/go-algorand/files/3734282/issue-283.tar.gz)
