### ISSUE TITLE
Goal / Algod crashing instantly with Go 1.17 build

### ISSUE THREAD

**Issue by pbennett** [algorand/go-algorand#2899]
### Subject of the issue

Building Algorand from source locally is creating binaries that instantly crash with Go 1.17 

### Your environment

Go 1.17 / darwin/amd64 [osx]
Pull from go-algorand, rel/stable branch
Full clean build (been done many many times over past 18 months - this is new behavior)

### Steps to reproduce

1. build prereqs
2. make clean / make install

Crashes as part of make install running goal/algod processes as part of pseudo-upgrade.

I'll attach the panic stack dump from running algod -v locally:
```
algod -v
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff20453c9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20453c9e
stack: frame={sp:0x7ffeefbff138, fp:0x7ffeefbff188} stack=[0x7ffeefb801d8,0x7ffeefbff240)
0x00007ffeefbff038:  0x01007ffeefbff058  0x0000000000000004
0x00007ffeefbff048:  0x000000000000001f  0x00007fff20453c9e
0x00007ffeefbff058:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff068:  0x000000000403a8d1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff108
0x00007ffeefbff078:  0x0000000004e08b5b  0x00007ffeefbff0c0
0x00007ffeefbff088:  0x000000000403ab88 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000056e84c0
0x00007ffeefbff098:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff0a8:  0x00007ffeefbff108  0x000000000403a8d1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff0b8:  0x00000000056e84c0  0x00007ffeefbff0f8
0x00007ffeefbff0c8:  0x000000000403ab10 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff0d8
0x00007ffeefbff0d8:  0x000000000403ab40 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000056e84c0
0x00007ffeefbff0e8:  0x000000000403a8d1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff108
0x00007ffeefbff0f8:  0x00007ffeefbff128  0x000000000403a8d1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff108:  0x00007ffeefbff110  0x000000000403a900 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff118:  0x0000000004e18633  0x000000000000002a
0x00007ffeefbff128:  0x00007ffeefbff178  0x0000000004050f76 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff138: <0x0000000004e18633  0x00000000056e84c0
0x00007ffeefbff148:  0x00007ffeefbff1b8  0x000000000402bc46 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff158:  0x000000c0001e2000  0x0000000000002000
0x00007ffeefbff168:  0x00007ffe00000008  0x000000000402c8f1 <runtime.addspecial+0x0000000000000191>
0x00007ffeefbff178:  0x00007ffeefbff1c0 !0x00007fff20453c9e
0x00007ffeefbff188: >0x00007ffeefbff1c0  0x000000000565c000
0x00007ffeefbff198:  0x0000000000000c00  0x000000000453d185 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff1a8:  0x000000000407053f <runtime.syscall+0x000000000000001f>  0x000000c00039f830
0x00007ffeefbff1b8:  0x00007ffeefbff200  0x000000c00039f800
0x00007ffeefbff1c8:  0x000000000406e370 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff1d8:  0x0000000004012e00 <runtime.persistentalloc+0x0000000000000060>  0x2e00000000001018
0x00007ffeefbff1e8:  0x0000000004031985 <runtime.mProf_Malloc.func1+0x0000000000000025>  0x000000000575fbb8
0x00007ffeefbff1f8:  0x0000000000000828  0x000000c0000001a0
0x00007ffeefbff208:  0x000000000406c489 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff218:  0x0000000004fc9068  0x00000000056e84c0
0x00007ffeefbff228:  0x00007ffeefbff270  0x000000000406c385 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff238:  0x000000000406c33d <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x4e18633, 0x56e84c0})
	runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20453c9e
stack: frame={sp:0x7ffeefbff138, fp:0x7ffeefbff188} stack=[0x7ffeefb801d8,0x7ffeefbff240)
0x00007ffeefbff038:  0x01007ffeefbff058  0x0000000000000004
0x00007ffeefbff048:  0x000000000000001f  0x00007fff20453c9e
0x00007ffeefbff058:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff068:  0x000000000403a8d1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff108
0x00007ffeefbff078:  0x0000000004e08b5b  0x00007ffeefbff0c0
0x00007ffeefbff088:  0x000000000403ab88 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000056e84c0
0x00007ffeefbff098:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff0a8:  0x00007ffeefbff108  0x000000000403a8d1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff0b8:  0x00000000056e84c0  0x00007ffeefbff0f8
0x00007ffeefbff0c8:  0x000000000403ab10 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff0d8
0x00007ffeefbff0d8:  0x000000000403ab40 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000056e84c0
0x00007ffeefbff0e8:  0x000000000403a8d1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff108
0x00007ffeefbff0f8:  0x00007ffeefbff128  0x000000000403a8d1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff108:  0x00007ffeefbff110  0x000000000403a900 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff118:  0x0000000004e18633  0x000000000000002a
0x00007ffeefbff128:  0x00007ffeefbff178  0x0000000004050f76 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff138: <0x0000000004e18633  0x00000000056e84c0
0x00007ffeefbff148:  0x00007ffeefbff1b8  0x000000000402bc46 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff158:  0x000000c0001e2000  0x0000000000002000
0x00007ffeefbff168:  0x00007ffe00000008  0x000000000402c8f1 <runtime.addspecial+0x0000000000000191>
0x00007ffeefbff178:  0x00007ffeefbff1c0 !0x00007fff20453c9e
0x00007ffeefbff188: >0x00007ffeefbff1c0  0x000000000565c000
0x00007ffeefbff198:  0x0000000000000c00  0x000000000453d185 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff1a8:  0x000000000407053f <runtime.syscall+0x000000000000001f>  0x000000c00039f830
0x00007ffeefbff1b8:  0x00007ffeefbff200  0x000000c00039f800
0x00007ffeefbff1c8:  0x000000000406e370 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff1d8:  0x0000000004012e00 <runtime.persistentalloc+0x0000000000000060>  0x2e00000000001018
0x00007ffeefbff1e8:  0x0000000004031985 <runtime.mProf_Malloc.func1+0x0000000000000025>  0x000000000575fbb8
0x00007ffeefbff1f8:  0x0000000000000828  0x000000c0000001a0
0x00007ffeefbff208:  0x000000000406c489 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff218:  0x0000000004fc9068  0x00000000056e84c0
0x00007ffeefbff228:  0x00007ffeefbff270  0x000000000406c385 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff238:  0x000000000406c33d <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
	runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x453d180, 0x1, 0x40487413, 0xc00039f8c0)
	runtime/sys_darwin.go:22 +0x3b fp=0xc00039f830 sp=0xc00039f810 pc=0x406af3b
syscall.syscall(0xc00039f8e0, 0xc00039f900, 0x4012714, 0x10000000406c46e)
	<autogenerated>:1 +0x26 fp=0xc00039f878 sp=0xc00039f830 pc=0x4070d06
golang.org/x/sys/unix.ioctl(0x18, 0x100000005a495b8, 0xdbb1910)
	golang.org/x/sys@v0.0.0-20200905004654-be1d3432aa8f/unix/zsyscall_darwin_amd64.go:746 +0x39 fp=0xc00039f8a8 sp=0xc00039f878 pc=0x453cc19
golang.org/x/sys/unix.IoctlGetTermios(...)
	golang.org/x/sys@v0.0.0-20200905004654-be1d3432aa8f/unix/ioctl.go:72
github.com/mattn/go-isatty.IsTerminal(0x4d04940)
	github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc00039f918 sp=0xc00039f8a8 pc=0x46d2d90
github.com/labstack/gommon/color.(*Color).SetOutput(0xc0000d0858, {0x4fdbc00, 0xc0000d8008})
	github.com/labstack/gommon@v0.3.0/color/color.go:146 +0x92 fp=0xc00039f938 sp=0xc00039f918 pc=0x46d31d2
github.com/labstack/gommon/color.New(...)
	github.com/labstack/gommon@v0.3.0/color/color.go:134
github.com/labstack/gommon/color.init()
	github.com/labstack/gommon@v0.3.0/color/color.go:102 +0x4ea fp=0xc00039f968 sp=0xc00039f938 pc=0x46d488a
runtime.doInit(0x56654c0)
	runtime/proc.go:6498 +0x123 fp=0xc00039faa0 sp=0xc00039f968 pc=0x404a1e3
runtime.doInit(0x566d160)
	runtime/proc.go:6475 +0x71 fp=0xc00039fbd8 sp=0xc00039faa0 pc=0x404a131
runtime.doInit(0x5668560)
	runtime/proc.go:6475 +0x71 fp=0xc00039fd10 sp=0xc00039fbd8 pc=0x404a131
runtime.doInit(0x566b280)
	runtime/proc.go:6475 +0x71 fp=0xc00039fe48 sp=0xc00039fd10 pc=0x404a131
runtime.doInit(0x566af00)
	runtime/proc.go:6475 +0x71 fp=0xc00039ff80 sp=0xc00039fe48 pc=0x404a131
runtime.main()
	runtime/proc.go:238 +0x1e6 fp=0xc00039ffe0 sp=0xc00039ff80 pc=0x403cf26
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc00039ffe8 sp=0xc00039ffe0 pc=0x406e661
```

**Comment by barnjamin** [comment]
https://github.com/labstack/gommon/issues/46 probably need to up the gommon version
