### ISSUE TITLE
Broken data dir after moving to new VM?

### ISSUE THREAD

**Issue by joltcan** [algorand/go-algorand#3236]
### Subject of the issue

I successfully installed algod in a new lxc Debian Bullseye container yesterday. Got everything synced and where doing great. Then I moved the install dir to another drive and something broke. Now as soon as I try to start algod I get this error:

```
Telemetry configured from '/home/algorand/node/data/logging.config'
Logging to:  /home/algorand/node/data/node.log
couldn't initialize the node: reloadLedger.loadFromDisk tracker *ledger.accountUpdates failed to loadFromDisk : transaction D7OPK2JYLNONEEWYWMVUZHQPCYSO246ZY2A4G3BF6MPHU27OVRXA: logic eval error: - would result negative
```
I know to little about this to even know where to start looking? Is it possible to remove that transaction if it partly added to sqlite or whatnot?

### Your environment

Algod installed via update.sh per official docs.
Ver: 12884901889
3.0.1.stable [rel/stable] (commit #b619b940)

Debian Bullseye amd64

### Steps to reproduce

1. algod -d ~/node/data/ or systemctl start algorand@...

### Expected behaviour

algod should start

### Actual behaviour

algod dies::

node.log:

```json 
Logging Starting
Telemetry Disabled
++++++++++++++++++++++++++++++++++++++++
{"file":"node.go","function":"github.com/algorand/go-algorand/node.MakeFull","level":"error","line":206,"msg":"[Stack] goroutine 1 [running]:\nruntime/debug.Stack(0xc000212070, 0xc000208008, 0xc0004860e0)\n\truntime/debug/stack.go:24 +0x9f\ngithub.com/algorand/go-algorand/logging.logger.Errorf(0xc000212070, 0xc000208008, 0x1299a77, 0x21, 0xc00334ff60, 0x2, 0x2)\n\tgithub.com/algorand/go-algorand/logging/log.go:229 +0x4a\ngithub.com/algorand/go-algorand/node.MakeFull(0x1ba27a0, 0xc000204040, 0x7ffe15c1672a, 0x18, 0x0, 0x4, 0x0, 0x0, 0xdf8475800, 0x0, ...)\n\tgithub.com/algorand/go-algorand/node/node.go:206 +0xf23\ngithub.com/algorand/go-algorand/daemon/algod.(*Server).Initialize(0xc00349fb68, 0x0, 0x4, 0x0, 0x0, 0xdf8475800, 0x0, 0x0, 0x1e, 0x0, ...)\n\tgithub.com/algorand/go-algorand/daemon/algod/server.go:127 +0x7df\nmain.run(0x0)\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:295 +0x1243\nmain.main()\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:61 +0x7b\n","time":"2021-11-20T10:46:53.076299+01:00"}
{"file":"node.go","function":"github.com/algorand/go-algorand/node.MakeFull","level":"error","line":206,"msg":"Cannot initialize ledger (/home/algorand/node/data/mainnet-v1.0/ledger): reloadLedger.loadFromDisk tracker *ledger.accountUpdates failed to loadFromDisk : transaction D7OPK2JYLNONEEWYWMVUZHQPCYSO246ZY2A4G3BF6MPHU27OVRXA: logic eval error: - would result negative","time":"2021-11-20T10:46:53.076476+01:00"}
{"file":"main.go","function":"main.run","level":"error","line":298,"msg":"[Stack] goroutine 1 [running]:\nruntime/debug.Stack(0xc000212070, 0xc000208008, 0xc000486380)\n\truntime/debug/stack.go:24 +0x9f\ngithub.com/algorand/go-algorand/logging.logger.Error(0xc000212070, 0xc000208008, 0xc00334ad30, 0x1, 0x1)\n\tgithub.com/algorand/go-algorand/logging/log.go:219 +0x4a\nmain.run(0x0)\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:298 +0x134b\nmain.main()\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:61 +0x7b\n","time":"2021-11-20T10:46:53.076572+01:00"}
{"file":"main.go","function":"main.run","level":"error","line":298,"msg":"couldn't initialize the node: reloadLedger.loadFromDisk tracker *ledger.accountUpdates failed to loadFromDisk : transaction D7OPK2JYLNONEEWYWMVUZHQPCYSO246ZY2A4G3BF6MPHU27OVRXA: logic eval error: - would result negative","time":"2021-11-20T10:46:53.076626+01:00"}
```

**Comment by joltcan** [comment]
Oh, is this related to https://github.com/algorand/go-algorand/pull/3214, I did use fast-catchup

**Comment by joltcan** [comment]
I found an old zfs snapshot, seems like it was enough to get it running. Something must have happened while I changed vm.
