### ISSUE TITLE
Algorand 3.2.1 node crashing with deadlock panic during normal catchup phase.

### ISSUE THREAD

**Issue by pbennett** [algorand/go-algorand#3312]
### Node routinely crashing with deadlock panic

I turned my archival node prior to going away on vacation.  Upon returning, I updated to latest version and restarted node. 
It is catching up from around the 17.5m mark.  
It starts catching up on old blocks successfully but after perhaps 5-10 minutes, it crashes, with a deadlock panic.

* Software version: 12885032961 / 3.2.1.stable [rel/stable] (commit #b6cbbf34)
* OSX Big Sur 11.6 (64-bit intel).

### Steps to reproduce

1. Start service...  
2. Wait..
3. Crash.   😀 

Log snippet of crash:
```
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":17880005,"Sender":"","Step":0,"Type":"RoundInterrupted","Weight":0,"WeightTotal":0,"file":"demux.go","function":"github.com/algorand/go-algorand/agreement.(*demux).next","level":"info","line":292,"msg":"agreement: round 17880005 ended early due to concurrent write; next round is 17880016","time":"2021-12-14T01:55:21.693409-05:00"}
{"file":"catchpointlabel.go","function":"github.com/algorand/go-algorand/ledger/ledgercore.CatchpointLabel.String","level":"info","line":60,"msg":"Creating a catchpoint label 17880000#AQRQRU2NTVUM5P7MNQ4N7X4F2X6EBRASB4THRJGAHC5E7EKGF6GA for round=17880000, block digest=MNF3GITGUJG4O3LWOHCGGQO46JWHN6NOSQ4NXUGZT4F3DB37ZUSQ, accounts digest=X2GDO5P4KIQNOBEDFN7LTKOBGXCFSK5AIXIALHWL2ZD7M3Y5MQGA","time":"2021-12-14T01:55:21.869643-05:00"}
{"file":"deadlockLogger.go","function":"github.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).onPotentialDeadlock.func1.1","level":"error","line":84,"msg":"[Stack] goroutine 7478561 [running]:\nruntime/debug.Stack(0xc0002da7e0, 0xc000126528, 0xc0179eae00)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/algorand/go-algorand/logging.logger.Error(0xc0002da7e0, 0xc000126528, 0xc010842d90, 0x1, 0x1)\n\tgithub.com/algorand/go-algorand/logging/log.go:219 +0x48\ngithub.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).onPotentialDeadlock.func1.1(0xc00013d4c0, 0xc014142000, 0xc03)\n\tgithub.com/algorand/go-algorand/daemon/algod/deadlockLogger.go:84 +0xa1\ncreated by github.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).onPotentialDeadlock.func1\n\tgithub.com/algorand/go-algorand/daemon/algod/deadlockLogger.go:83 +0x1d1\n","time":"2021-12-14T01:55:51.751153-05:00"}
{"file":"deadlockLogger.go","function":"github.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).onPotentialDeadlock.func1.1","level":"error","line":84,"msg":"POTENTIAL DEADLOCK:\nPrevious place where the lock was grabbed\ngoroutine 206 lock 0xc0001d7f70\ngithub.com/algorand/go-algorand/ledger/ledger.go:396 ledger.(*Ledger).notifyCommit ??? \u003c\u003c\u003c\u003c\u003c\ngithub.com/algorand/go-algorand/ledger/blockqueue.go:145 ledger.(*blockQueue).syncer ???\n\nHave been trying to lock it again for more than 30s\ngoroutine 152 lock 0xc0001d7f70\ngithub.com/algorand/go-algorand/ledger/ledger.go:478 ledger.(*Ledger).LookupAgreement ??? \u003c\u003c\u003c\u003c\u003c\ngithub.com/algorand/go-algorand/agreement/selector.go:67 agreement.membership ???\ngithub.com/algorand/go-algorand/agreement/vote.go:91 agreement.unauthenticatedVote.verify ???\ngithub.com/algorand/go-algorand/agreement/asyncVoteVerifier.go:106 agreement.(*AsyncVoteVerifier).executeVoteVerification ???\ngithub.com/algorand/go-algorand/util/execpool/pool.go:159 execpool.(*pool).worker ???\n\nHere is what goroutine 206 doing now\ngoroutine 206 [chan send]:\ngithub.com/algorand/go-algorand/ledger.(*trackerRegistry).scheduleCommit(0xc0001d7e78, 0x110d3ce, 0x140)\n\tgithub.com/algorand/go-algorand/ledger/tracker.go:340 +0x1f4\ngithub.com/algorand/go-algorand/ledger.(*trackerRegistry).committedUpTo(0xc0001d7e78, 0x110d3ce, 0xc027765d28)\n\tgithub.com/algorand/go-algorand/ledger/tracker.go:302 +0xe0\ngithub.com/algorand/go-algorand/ledger.(*Ledger).notifyCommit(0xc0001d7800, 0x110d3ce, 0x0)\n\tgithub.com/algorand/go-algorand/ledger/ledger.go:398 +0x8d\ngithub.com/algorand/go-algorand/ledger.(*blockQueue).syncer(0xc0000a4320)\n\tgithub.com/algorand/go-algorand/ledger/blockqueue.go:145 +0x3df\ncreated by github.com/algorand/go-algorand/ledger.bqInit\n\tgithub.com/algorand/go-algorand/ledger/blockqueue.go:72 +0x21d\nOther goroutines holding locks:\ngoroutine 213 lock a\ngithub.com/algorand/go-algorand/ledger/tracker.go:467 ledger.(*trackerRegistry).commitRound ??? \u003c\u003c\u003c\u003c\u003c\ngithub.com/algorand/go-algorand/ledger/tracker.go:378 ledger.(*trackerRegistry).commitSyncer ???\n\ngoroutine 10421 lock 21\ngithub.com/algorand/go-algorand/node/node.go:668 node.(*AlgorandFullNode).Status ??? \u003c\u003c\u003c\u003c\u003c\ngithub.com/algorand/go-algorand/daemon/algod/api/server/v2/handlers.go:401 v2.(*Handlers).GetStatus ???\ngithub.com/algorand/go-algorand/daemon/algod/api/server/v2/generated/routes.go:365 generated.(*ServerInterfaceWrapper).GetStatus ???\ngithub.com/algorand/go-algorand/daemon/algod/api/server/lib/middlewares/auth.go:100 middlewares.(*AuthMiddleware).handler.func1 ???\ngithub.com/labstack/echo/v4@v4.1.17/echo.go:522 v4.(*Echo).add.func1 ???\ngithub.com/labstack/echo/v4@v4.1.17/middleware/cors.go:121 middleware.CORSWithConfig.func1.1 ???\ngithub.com/algorand/go-algorand/daemon/algod/api/server/lib/middlewares/logger.go:52 middlewares.(*LoggerMiddleware).handler.func1 ???\ngithub.com/labstack/echo/v4@v4.1.17/echo.go:627 v4.(*Echo).ServeHTTP.func1 ???\ngithub.com/labstack/echo/v4@v4.1.17/middleware/slash.go:118 middleware.RemoveTrailingSlashWithConfig.func1.1 ???\ngithub.com/labstack/echo/v4@v4.1.17/echo.go:633 v4.(*Echo).ServeHTTP ???\nnet/http/server.go:2836 http.serverHandler.ServeHTTP ???\nnet/http/server.go:1924 http.(*conn).serve ???\n\n\n\n","time":"2021-12-14T01:55:51.779865-05:00"}
{"file":"deadlockLogger.go","function":"github.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).Panic","level":"error","line":41,"msg":"[Stack] goroutine 7478561 [running]:\nruntime/debug.Stack(0xc0002da7e0, 0xc000126528, 0xc0179eb0a0)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/algorand/go-algorand/logging.logger.Panic(0xc0002da7e0, 0xc000126528, 0xc009b60b00, 0x1, 0x1)\n\tgithub.com/algorand/go-algorand/logging/log.go:255 +0x7b\ngithub.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).Panic(...)\n\tgithub.com/algorand/go-algorand/daemon/algod/deadlockLogger.go:41\ngithub.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).onPotentialDeadlock.func1.1(0xc00013d4c0, 0xc014142000, 0xc03)\n\tgithub.com/algorand/go-algorand/daemon/algod/deadlockLogger.go:85 +0xaf\ncreated by github.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).onPotentialDeadlock.func1\n\tgithub.com/algorand/go-algorand/daemon/algod/deadlockLogger.go:83 +0x1d1\n","time":"2021-12-14T01:55:51.780000-05:00"}
{"file":"deadlockLogger.go","function":"github.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).Panic","level":"panic","line":41,"msg":"potential deadlock detected","time":"2021-12-14T01:55:51.780087-05:00"}
```

**Comment by onetechnical** [comment]
Did you explicitly enable deadlock detection in the config?

**Comment by onetechnical** [comment]
@pbennett can you include your config.json? Is this using the released 3.2.1 tar.gz darwin binary?

**Comment by pbennett** [comment]
Yes, using the 3.2.1 darwin binary installed via the update.sh script.
```
{
	"Archival": true,
	"EndpointAddress": "127.0.0.1:8081",
	"EnableDeveloperAPI": true
}
```

I ended up having to set DeadlockDetection to -1 to force the (broken) deadlock detection code from being disabled.
Your darwin build is presumably setting DeadlockDetection to true in the build itself via the -X flags in the makefile since it forces it on by default.

**Comment by onetechnical** [comment]
@pbennett Has this problem gone away with the 3.2.3-stable release?

**Comment by pbennett** [comment]
Looks like it, yes.
