### ISSUE TITLE
algorand mainnet restarts approx twice daily : memory leak ? 

### ISSUE THREAD

**Issue by charveepunia** [algorand/go-algorand#3387]
### Subject of the issue

Hi, I'm running Algorand nodes, since few days the Algorand mainnet restarts often approx twice daily, is there a memory leak issue.

### Your environment
Software version: algod version=3.2.1 indexer version=2.8.0
Node : running currently 
OS: 20.04.1-Ubuntu CPU: 4000MHz and RAM 11000 MiB, running node with "Archival": true

logs 
```
 panic: (*logrus.Entry) (0x1b4d0e0,0xc012ae1ab0) [recovered]
    panic: (*logrus.Entry) (0x1b4d0e0,0xc012ae1ab0)

goroutine 87032324 [running]:
github.com/algorand/go-algorand/logging.logger.Panic.func1(0xc00032c7e0, 0xc000010548)
    github.com/algorand/go-algorand/logging/log.go:252 +0x89
panic(0x1b4d0e0, 0xc012ae1ab0)
    runtime/panic.go:969 +0x16a
github.com/sirupsen/logrus.Entry.log(0xc00032c770, 0xc008e44ff0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2dc
github.com/sirupsen/logrus.(*Entry).Log(0xc012ae1a40, 0x0, 0xc0225108d0, 0x1, 0x1)
    github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xed
github.com/sirupsen/logrus.(*Entry).Panic(0xc012ae1a40, 0xc0225108d0, 0x1, 0x1)
    github.com/sirupsen/logrus@v1.4.2/entry.go:306 +0x57
github.com/algorand/go-algorand/logging.logger.Panic(0xc00032c7e0, 0xc000010548, 0xc0225108d0, 0x1, 0x1)
    github.com/algorand/go-algorand/logging/log.go:256 +0x178
github.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).Panic(...)
    github.com/algorand/go-algorand/daemon/algod/deadlockLogger.go:41
github.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).onPotentialDeadlock.func1.1(0xc000222f00, 0xc01a573000, 0x1600)
    github.com/algorand/go-algorand/daemon/algod/deadlockLogger.go:85 +0xb1
created by github.com/algorand/go-algorand/daemon/algod.(*deadlockLogger).onPotentialDeadlock.func1
    github.com/algorand/go-algorand/daemon/algod/deadlockLogger.go:83 +0x1d3 
```

### Steps to reproduce

1.
2.

### Expected behaviour
no restarts 
### Actual behaviour
the algod restarts almost twice daily for mainnet

**Comment by charveepunia** [comment]
upgrade to 3.2.3
