### ISSUE TITLE
Test Flakiness: agreement integration on travis

### ISSUE THREAD

**Issue by Vervious** [algorand/go-algorand#34]
Seen on travis: 

```
node-0:
 demuxCoserviceType: 1
 pseudonodeCoserviceType: 1
 clockCoserviceType: 0
--- FAIL: TestAgreementSynchronous1 (0.23s)
panic: unexpected number of zeroes: 3 != 4 [recovered]
	panic: unexpected number of zeroes: 3 != 4 [recovered]
	panic: unexpected number of zeroes: 3 != 4
goroutine 35561 [running]:
testing.tRunner.func1(0xc001f2ae00)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/testing/testing.go:830 +0x68a
panic(0x1232640, 0xc002a83070)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/algorand/go-algorand/agreement.setupAgreement.func1()
	/home/travis/gopath/src/github.com/algorand/go-algorand/agreement/service_test.go:765 +0x2eb
panic(0x1232640, 0xc002a83070)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/algorand/go-algorand/agreement.expectNewPeriod(0xc0023a6a50, 0x1, 0x1, 0x4, 0xc0020a17c0)
	/home/travis/gopath/src/github.com/algorand/go-algorand/agreement/service_test.go:804 +0x1f8
github.com/algorand/go-algorand/agreement.runRound(0xc0023a6a50, 0x1, 0x1, 0xc0020a17c0, 0x3, 0x3)
	/home/travis/gopath/src/github.com/algorand/go-algorand/agreement/service_test.go:833 +0xa3
github.com/algorand/go-algorand/agreement.simulateAgreementWithLedgerFactory(0xc001f2ae00, 0x1, 0x5, 0x0, 0x13ff1a8)
	/home/travis/gopath/src/github.com/algorand/go-algorand/agreement/service_test.go:870 +0x28f
github.com/algorand/go-algorand/agreement.simulateAgreement(...)
	/home/travis/gopath/src/github.com/algorand/go-algorand/agreement/service_test.go:854
github.com/algorand/go-algorand/agreement.TestAgreementSynchronous1(0xc001f2ae00)
	/home/travis/gopath/src/github.com/algorand/go-algorand/agreement/service_test.go:885 +0x61
testing.tRunner(0xc001f2ae00, 0x13fed30)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/testing/testing.go:916 +0x69a
FAIL	github.com/algorand/go-algorand/agreement	100.978s
Makefile:194: recipe for target 'short_test_target_github.com/algorand/go-algorand/agreement' failed
```

Note that the system is inherently nondeterministic, and travis is a particularly finicky execution environment. Nonetheless we should investigate and put more effort into more deterministic tests. I cannot replicate this locally running `-test.count 10000` times.

(Note: travis artifacts are currently broken. As is, we have no information to debug. We should revisit when we see another failure and have corresponding cadaver and log files to debug.)

**Comment by Vervious** [comment]
Closing since we haven't seen this for a while. Re-open (with appropriate cadaver and log files) if reoccurs.
