### ISSUE TITLE
Error while validating block on raspberry-pi 32 bit

### ISSUE THREAD

**Issue by id-ms** [algorand/go-algorand#3987]
### Subject of the issue

Running alogd on a raspberry pi produce the following error log:

```
{
  "file": "ledger.go",
  "function": "github.com/algorand/go-algorand/data.(*Ledger).EnsureBlock",
  "level": "error",
  "line": 367,
  "msg": "[Stack] goroutine 4452 [running]:\nruntime/debug.Stack(0x85143040, 0x84c111f0, 0x971d9280)\n\truntime/debug/stack.go:24 +0x80\ngithub.com/algorand/go-algorand/logging.logger.Errorf(0x85143040, 0x84c111f0, 0xb61720e4, 0x3c, 0x87e6cf10, 0x2, 0x2)\n\tgithub.com/algorand/go-algorand/logging/log.go:229 +0x30\ngithub.com/algorand/go-algorand/data.(*Ledger).EnsureBlock(0x85111020, 0x81740800, 0x13d4345, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, 0x0, ...)\n\tgithub.com/algorand/go-algorand/data/ledger.go:367 +0x2f8\ngithub.com/algorand/go-algorand/catchup.(*Service).fetchRound(0x911c0a00, 0x13d4345, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, 0x0, 0x296b4cd2, ...)\n\tgithub.com/algorand/go-algorand/catchup/service.go:682 +0xb44\ngithub.com/algorand/go-algorand/catchup.(*Service).syncCert(...)\n\tgithub.com/algorand/go-algorand/catchup/service.go:641\ngithub.com/algorand/go-algorand/catchup.(*Service).periodicSync(0x911c0a00)\n\tgithub.com/algorand/go-algorand/catchup/service.go:570 +0x4f4\ncreated by github.com/algorand/go-algorand/catchup.(*Service).Start\n\tgithub.com/algorand/go-algorand/catchup/service.go:128 +0xf0\n",
  "name": "",
  "time": "2022-05-12T03:02:32.013619-04:00"
}

{
  "file": "ledger.go",
  "function": "github.com/algorand/go-algorand/data.(*Ledger).EnsureBlock",
  "level": "error",
  "line": 367,
  "msg": "data.EnsureBlock: could not write block 20792133 to the ledger: transaction 3CEX7MRWDS3WOLDSGQFLJMYCSZG3XFIY6DHNQYE7GOWOMEOVUQEQ: logic eval error: assert failed pc=398. Details: pc=398, opcodes=gtxn 3 AssetAmount\n>=\nassert\n",
  "name": "",
  "time": "2022-05-12T03:02:32.013808-04:00"
}
```

it fails while trying to assert the following group:
 https://algoexplorer.io/tx/group/s40nN23Ap5NOk2sHjrMn0o2sBLTxrSuMH6LzE6rzi%2Bw%3D

### Your environment

algod - 3.5.1
network -  mainnet-v1.0
OS - raspberry pi 32 bit

**Comment by onetechnical** [comment]
We are no longer supporting 32-bit builds.
