### ISSUE TITLE
sandbox tealdbg crashes when debugging a smart contract

### ISSUE THREAD

**Issue by andreademasi** [algorand/go-algorand#4057]
### Subject of the issue
I'm not able to debug a smart contract with tealdbg included in the sandbox. I tried even the ones in the [samples folder](https://github.com/algorand/go-algorand/tree/master/cmd/tealdbg/samples) with no luck, i kept getting a stack trace similar to the one included here:

<details>
  <summary>Stacktrace</summary>

```
❯ ./sandbox tealdbg debug main.teal
tealdbg debug command called without --listen option therefore sandbox attached the option automatically!
2022/05/31 10:08:23 Using proto: https://github.com/algorandfoundation/specs/tree/d5ac876d7ede07367dbaa26e149aa42589aac1f7
2022/05/31 10:08:23 Run mode: stateful
ERRO[0000] [Stack] goroutine 1 [running]:
runtime/debug.Stack(0xc0004271f0, 0xc0000980e8, 0xc000414620)
	runtime/debug/stack.go:24 +0x9f
github.com/algorand/go-algorand/logging.logger.Errorf(0xc0004271f0, 0xc0000980e8, 0x101b87f, 0x1b, 0xc0007426f0, 0x1, 0x1)
	github.com/algorand/go-algorand/logging/log.go:229 +0x4a
github.com/algorand/go-algorand/data/transactions/logic.eval.func1(0xc00039d440, 0xc000502500, 0xc00039d448)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:674 +0x232
panic(0x14db440, 0x1ab82d0)
	runtime/panic.go:971 +0x499
github.com/algorand/go-algorand/data/transactions/logic.(*EvalContext).refreshDebugState(0xc000502500, 0x0, 0x0, 0x46cbc0)
	github.com/algorand/go-algorand/data/transactions/logic/debugger.go:229 +0x62
github.com/algorand/go-algorand/data/transactions/logic.eval.func2(0xc000502500, 0xc00039d448)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:681 +0x5d
panic(0x14db5c0, 0x160c970)
	runtime/panic.go:971 +0x499
github.com/algorand/go-algorand/data/transactions/logic.(*EvalContext).getApplicationAddress(0xc000502500, 0x52414e44, 0x0, 0x0, 0x0, 0x0)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:2787 +0x17b
github.com/algorand/go-algorand/data/transactions/logic.(*EvalContext).globalFieldToValue(0xc000502500, 0xa, 0x3, 0x2, 0x5, 0x102d1d1, 0x2d, 0x0, 0x0, 0x0, ...)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:2824 +0x40b
github.com/algorand/go-algorand/data/transactions/logic.makeDebugState(0xc000502500, 0x0)
	github.com/algorand/go-algorand/data/transactions/logic/debugger.go:121 +0x3a7
github.com/algorand/go-algorand/data/transactions/logic.eval(0xc00043a480, 0x213, 0x213, 0xc000502500, 0x7fcb48252800, 0x161cac8, 0xc0004a2640)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:712 +0x793
github.com/algorand/go-algorand/data/transactions/logic.EvalContract(0xc00043a480, 0x213, 0x213, 0x0, 0x52414e44, 0xc0004c2240, 0x203000, 0x203000, 0x1, 0x203000)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:630 +0x1b6
github.com/algorand/go-algorand/ledger/internal.(*roundCowState).StatefulEval(0xc000581000, 0x0, 0xc0004c2240, 0x52414e44, 0xc00043a480, 0x213, 0x213, 0xc000020fa0, 0x0, 0x0, ...)
	github.com/algorand/go-algorand/ledger/internal/appcow.go:467 +0x125
main.(*evaluation).eval(0xc0004300f0, 0x0, 0xc0004c2240, 0xc00043a480, 0x213, 0x213)
	github.com/algorand/go-algorand/cmd/tealdbg/local.go:242 +0x139
main.(*LocalRunner).RunAll(0xc0004bc300, 0xc000430000, 0x0)
	github.com/algorand/go-algorand/cmd/tealdbg/local.go:557 +0x225
main.(*DebugServer).startDebug(0xc0000a0680, 0x0, 0x0)
	github.com/algorand/go-algorand/cmd/tealdbg/server.go:191 +0x2b8
main.debugLocal(0xc0004938c0, 0x1, 0x3)
	github.com/algorand/go-algorand/cmd/tealdbg/main.go:251 +0x5c5
main.glob..func2(0x1ac2c80, 0xc0004938c0, 0x1, 0x3)
	github.com/algorand/go-algorand/cmd/tealdbg/main.go:53 +0x45
github.com/spf13/cobra.(*Command).execute(0x1ac2c80, 0xc000493830, 0x3, 0x3, 0x1ac2c80, 0xc000493830)
	github.com/spf13/cobra@v0.0.3/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1ac27c0, 0xdb07a0, 0x0, 0x0)
	github.com/spf13/cobra@v0.0.3/command.go:852 +0x308
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	github.com/algorand/go-algorand/cmd/tealdbg/main.go:31 +0x33  file=eval.go function=github.com/algorand/go-algorand/data/transactions/logic.eval.func1 line=674
ERRO[0000] recovered panic in Eval: %!w(logic.PanicError={invalid memory address or nil pointer dereference goroutine 1 [running]:
github.com/algorand/go-algorand/data/transactions/logic.eval.func1(0xc00039d440, 0xc000502500, 0xc00039d448)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:667 +0xbd
panic(0x14db440, 0x1ab82d0)
	runtime/panic.go:971 +0x499
github.com/algorand/go-algorand/data/transactions/logic.(*EvalContext).refreshDebugState(0xc000502500, 0x0, 0x0, 0x46cbc0)
	github.com/algorand/go-algorand/data/transactions/logic/debugger.go:229 +0x62
github.com/algorand/go-algorand/data/transactions/logic.eval.func2(0xc000502500, 0xc00039d448)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:681 +0x5d
panic(0x14db5c0, 0x160c970)
	runtime/panic.go:971 +0x499
github.com/algorand/go-algorand/data/transactions/logic.(*EvalContext).getApplicationAddress(0xc000502500, 0x52414e44, 0x0, 0x0, 0x0, 0x0)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:2787 +0x17b
github.com/algorand/go-algorand/data/transactions/logic.(*EvalContext).globalFieldToValue(0xc000502500, 0xa, 0x3, 0x2, 0x5, 0x102d1d1, 0x2d, 0x0, 0x0, 0x0, ...)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:2824 +0x40b
github.com/algorand/go-algorand/data/transactions/logic.makeDebugState(0xc000502500, 0x0)
	github.com/algorand/go-algorand/data/transactions/logic/debugger.go:121 +0x3a7
github.com/algorand/go-algorand/data/transactions/logic.eval(0xc00043a480, 0x213, 0x213, 0xc000502500, 0x7fcb48252800, 0x0, 0x0)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:712 +0x793
github.com/algorand/go-algorand/data/transactions/logic.EvalContract(0xc00043a480, 0x213, 0x213, 0x0, 0x52414e44, 0xc0004c2240, 0x203000, 0x203000, 0x1, 0x203000)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:630 +0x1b6
github.com/algorand/go-algorand/ledger/internal.(*roundCowState).StatefulEval(0xc000581000, 0x0, 0xc0004c2240, 0x52414e44, 0xc00043a480, 0x213, 0x213, 0xc000020fa0, 0x0, 0x0, ...)
	github.com/algorand/go-algorand/ledger/internal/appcow.go:467 +0x125
main.(*evaluation).eval(0xc0004300f0, 0x0, 0xc0004c2240, 0xc00043a480, 0x213, 0x213)
	github.com/algorand/go-algorand/cmd/tealdbg/local.go:242 +0x139
main.(*LocalRunner).RunAll(0xc0004bc300, 0xc000430000, 0x0)
	github.com/algorand/go-algorand/cmd/tealdbg/local.go:557 +0x225
main.(*DebugServer).startDebug(0xc0000a0680, 0x0, 0x0)
	github.com/algorand/go-algorand/cmd/tealdbg/server.go:191 +0x2b8
main.debugLocal(0xc0004938c0, 0x1, 0x3)
	github.com/algorand/go-algorand/cmd/tealdbg/main.go:251 +0x5c5
main.glob..func2(0x1ac2c80, 0xc0004938c0, 0x1, 0x3)
	github.com/algorand/go-algorand/cmd/tealdbg/main.go:53 +0x45
github.com/spf13/cobra.(*Command).execute(0x1ac2c80, 0xc000493830, 0x3, 0x3, 0x1ac2c80, 0xc000493830)
	github.com/spf13/cobra@v0.0.3/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1ac27c0, 0xdb07a0, 0x0, 0x0)
	github.com/spf13/cobra@v0.0.3/command.go:852 +0x308
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	github.com/algorand/go-algorand/cmd/tealdbg/main.go:31 +0x33
})  file=eval.go function=github.com/algorand/go-algorand/data/transactions/logic.eval.func1 line=674
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/algorand/go-algorand/data/transactions/logic.EvalContract(0xc00043a480, 0x213, 0x213, 0x0, 0x52414e44, 0xc0004c2240, 0x203000, 0x203000, 0x1, 0x203000)
	github.com/algorand/go-algorand/data/transactions/logic/eval.go:638 +0x591
github.com/algorand/go-algorand/ledger/internal.(*roundCowState).StatefulEval(0xc000581000, 0x0, 0xc0004c2240, 0x52414e44, 0xc00043a480, 0x213, 0x213, 0xc000020fa0, 0x0, 0x0, ...)
	github.com/algorand/go-algorand/ledger/internal/appcow.go:467 +0x125
main.(*evaluation).eval(0xc0004300f0, 0x0, 0xc0004c2240, 0xc00043a480, 0x213, 0x213)
	github.com/algorand/go-algorand/cmd/tealdbg/local.go:242 +0x139
main.(*LocalRunner).RunAll(0xc0004bc300, 0xc000430000, 0x0)
	github.com/algorand/go-algorand/cmd/tealdbg/local.go:557 +0x225
main.(*DebugServer).startDebug(0xc0000a0680, 0x0, 0x0)
	github.com/algorand/go-algorand/cmd/tealdbg/server.go:191 +0x2b8
main.debugLocal(0xc0004938c0, 0x1, 0x3)
	github.com/algorand/go-algorand/cmd/tealdbg/main.go:251 +0x5c5
main.glob..func2(0x1ac2c80, 0xc0004938c0, 0x1, 0x3)
	github.com/algorand/go-algorand/cmd/tealdbg/main.go:53 +0x45
github.com/spf13/cobra.(*Command).execute(0x1ac2c80, 0xc000493830, 0x3, 0x3, 0x1ac2c80, 0xc000493830)
	github.com/spf13/cobra@v0.0.3/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1ac27c0, 0xdb07a0, 0x0, 0x0)
	github.com/spf13/cobra@v0.0.3/command.go:852 +0x308
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	github.com/algorand/go-algorand/cmd/tealdbg/main.go:31 +0x33
```
</details>

### Your environment

* Software version: 3.6.2.stable [rel/stable] (commit #5e6bc6fc)
* Node status if applicable: 
```
Last committed block: 465
Time since last block: 1.9s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/d5ac876d7ede07367dbaa26e149aa42589aac1f7
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/d5ac876d7ede07367dbaa26e149aa42589aac1f7
Round for next consensus protocol: 466
Next consensus protocol supported: true
Last Catchpoint: 
Genesis ID: sandnet-v1
Genesis hash: +Kt49Kg2hPGRlt3igdBRceD9+m6B1zGTrl9z9/otbVA=
```

* Operating System details. 
Arch Linux x86_64,  Kernel: 5.18.0-arch1-1

### Steps to reproduce

1. Run sandbox: `./sandbox up`
2. Copy any smart contract into algod container: `./sandbox copyTo calls_count.teal`
3. Run debugger `./sandbox tealdbg debug calls_count.teal`

### Expected behaviour
Debugger running
### Actual behaviour
Debugger crashing

**Comment by andreademasi** [comment]
Documentation was a bit misleading, you need to pass a dryrun dump.
