### ISSUE TITLE
Node is not processing blocks

### ISSUE THREAD

**Issue by aelg** [algorand/go-algorand#4763]
### Node is not processing blocks

Node has stopped processing blocks. Is is logging the following error:
```
{"file":"ledger.go","function":"github.com/algorand/go-algorand/data.(*Ledger).EnsureBlock","level":"error","line":367,"msg":"[Stack] goroutine 278 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x78\ngithub.com/algorand/go-algorand/logging.logger.Errorf({0x2048a80, 0x1c9f990}, {0xf189c9, 0x3c}, {0x2758d9f0, 0x2, 0x2})\n\tgithub.com/algorand/go-algorand/logging/log.go:229 +0x30\ngithub.com/algorand/go-algorand/data.(*Ledger).EnsureBlock(0x1c0d0a0, 0x536086c0, {{}, 0x177b62b, 0x0, 0x2, {{}, 0x0, {0x1, 0xfa, ...}, ...}, ...})\n\tgithub.com/algorand/go-algorand/data/ledger.go:367 +0x30c\ngithub.com/algorand/go-algorand/catchup.(*Service).fetchRound(0xed71900, {{}, 0x177b62b, 0x0, 0x2, {{}, 0x0, {0x1, 0xfa, 0xd5, ...}, ...}, ...}, ...)\n\tgithub.com/algorand/go-algorand/catchup/service.go:682 +0xc10\ngithub.com/algorand/go-algorand/catchup.(*Service).syncCert(...)\n\tgithub.com/algorand/go-algorand/catchup/service.go:641\ngithub.com/algorand/go-algorand/catchup.(*Service).periodicSync(0xed71900)\n\tgithub.com/algorand/go-algorand/catchup/service.go:570 +0x484\ncreated by github.com/algorand/go-algorand/catchup.(*Service).Start\n\tgithub.com/algorand/go-algorand/catchup/service.go:128 +0x10c\n","name":"","time":"2022-11-05T16:50:15.723962Z"}
{"file":"ledger.go","function":"github.com/algorand/go-algorand/data.(*Ledger).EnsureBlock","level":"error","line":367,"msg":"data.EnsureBlock: could not write block 24622635 to the ledger: transaction YW4RP43UJ67RJEOLJPFJBDBJZE6YIXR5ZUETNASXV6SOFVVIJD5A: underflow on subtracting 20719195289 from sender amount 20719195288","name":"","time":"2022-11-05T16:50:15.724367Z"}
```

Restarting the node does not help, it goes into a resync loop which seem to hang because of the same error.

```
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"warning","line":300,"msg":"fetchAndWrite(24622647): lookback block doesn't exist, cannot authenticate new block","name":"","time":"2022-11-05T17:27:32.490558Z"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).pipelineCallback.func1","level":"info","line":404,"msg":"pipelineCallback(24622647): did not fetch or write the block","name":"","time":"2022-11-05T17:27:32.490741Z"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"warning","line":300,"msg":"fetchAndWrite(24622649): lookback block doesn't exist, cannot authenticate new block","name":"","time":"2022-11-05T17:27:32.490825Z"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).pipelineCallback.func1","level":"info","line":404,"msg":"pipelineCallback(24622649): did not fetch or write the block","name":"","time":"2022-11-05T17:27:32.490906Z"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).sync","level":"info","line":634,"msg":"Catchup Service: finished catching up, now at round 24622634 (previously 24622634). Total time catching up 325.429493ms.","name":"","time":"2022-11-05T17:27:32.491007Z"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).periodicSync","level":"info","line":562,"msg":"It's been too long since our ledger advanced; resyncing","name":"","time":"2022-11-05T17:27:49.491513Z"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"error","line":378,"msg":"[Stack] goroutine 3338 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x78\ngithub.com/algorand/go-algorand/logging.logger.Errorf({0x206c640, 0x2010808}, {0xf07fe2, 0x2a}, {0xd9eab60, 0x2, 0x2})\n\tgithub.com/algorand/go-algorand/logging/log.go:229 +0x30\ngithub.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite(0xc348a00, 0x177b62b, 0xb3919c0, 0xb391980, 0x11d471c0)\n\tgithub.com/algorand/go-algorand/catchup/service.go:378 +0x1848\ngithub.com/algorand/go-algorand/catchup.(*Service).pipelineCallback.func1()\n\tgithub.com/algorand/go-algorand/catchup/service.go:397 +0x58\ngithub.com/algorand/go-algorand/catchup.(*Service).pipelinedFetch.func2(0xfd7f7d0, 0x11d47140, 0x11459b00)\n\tgithub.com/algorand/go-algorand/catchup/service.go:441 +0x5c\ncreated by github.com/algorand/go-algorand/catchup.(*Service).pipelinedFetch\n\tgithub.com/algorand/go-algorand/catchup/service.go:438 +0x264\n","name":"","time":"2022-11-05T17:27:49.873810Z"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"error","line":378,"msg":"fetchAndWrite(24622635): ledger write failed: transaction YW4RP43UJ67RJEOLJPFJBDBJZE6YIXR5ZUETNASXV6SOFVVIJD5A: underflow on subtracting 20719195289 from sender amount 20719195288","name":"","time":"2022-11-05T17:27:49.873974Z"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).pipelineCallback.func1","level":"info","line":404,"msg":"pipelineCallback(24622635): did not fetch or write the block","name":"","time":"2022-11-05T17:27:49.874061Z"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"warning","line":300,"msg":"fetchAndWrite(24622637): lookback block doesn't exist, cannot authenticate new block","name":"","time":"2022-11-05T17:27:49.874091Z"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"warning","line":386,"msg":"fetchAndWrite(24622636): previous block doesn't exist (perhaps fetching block 24622635 failed)","name":"","time":"2022-11-05T17:27:49.874163Z"}
```

### My environment

```
$ algod -v
12885622786
3.11.2.stable [rel/stable] (commit #99b37ac0)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

```
$ goal node status
Last committed block: 24622634
Time since last block: 0.0s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/433d8e9a7274b6fca703d91213e05c7e6a589e69
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/433d8e9a7274b6fca703d91213e05c7e6a589e69
Round for next consensus protocol: 24622635
Next consensus protocol supported: true
Last Catchpoint:
Genesis ID: mainnet-v1.0
Genesis hash: wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=
```

```
uname -a
Linux alarmpi 5.15.72-1-rpi-ARCH #1 SMP Wed Oct 5 06:35:43 MDT 2022 armv7l GNU/Linux
```

**Comment by winder** [comment]
Is this still an issue?

**Comment by aelg** [comment]
@winder No, it's not still an issue, I think it resolved itself when a new catchpoint was available. I also switched to arm64 around that same time, haven't had any issues since then.
