### ISSUE TITLE
Node panic on start, panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by aelg** [algorand/go-algorand#4855]
After upgrade to 3.12.2 node panics on startup

```
$ algod -v
12885688322
3.12.2.stable [rel/stable] (commit #181490e3)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

```
$ uname -a
Linux alarmpi 5.15.79-2-rpi-ARCH #1 SMP Sat Nov 19 09:07:48 MST 2022 armv7l GNU/Linux
```

### Steps to reproduce

Start node, it immediately panics with the following log:
```
Telemetry configured from '*****/mainnet/logging.config'
Logging to:  *****/mainnet/node.log
panic: unaligned 64-bit atomic operation
goroutine 257 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x314b9b4, 0xffffffffffffffff)
        runtime/internal/atomic/atomic_arm.s:256 +0x14
github.com/algorand/go-algorand/ledger/internal/prefetcher.(*groupTask).markCompletionResource(...)
        github.com/algorand/go-algorand/ledger/internal/prefetcher/prefetcher.go:468
github.com/algorand/go-algorand/ledger/internal/prefetcher.(*accountPrefetcher).asyncPrefetchRoutine(0x83ee2c0, 0xa>
        github.com/algorand/go-algorand/ledger/internal/prefetcher/prefetcher.go:577 +0x75c
created by github.com/algorand/go-algorand/ledger/internal/prefetcher.(*accountPrefetcher).prefetch
        github.com/algorand/go-algorand/ledger/internal/prefetcher/prefetcher.go:401 +0x7c4
```

**Comment by mattstover83** [comment]
I too have also experienced this .. again. Looking into wiping my raspberry pi and starting fresh with their 64-bit OS.

**Comment by elricWu** [comment]
If you encounter difficulties in building algo node, you may use this public node. 
As follow:
curl --location --request GET 'https://rhizome.ebtoken.io/algo/v1/status' \
--header 'x-api-key: ee58601e-45c7-47e8-a4fa-00f8ec0cd059' \
--header 'Content-Type: application/json'
