### ISSUE TITLE
accountList.json: no such file or directory in private network with betanet

### ISSUE THREAD

**Issue by wisthsb1519** [algorand/go-algorand#570]
Error when working with wallets and accounts in a private network with betanet binaries. Specifically when creating wallets and accounts. They do, ultimately, get created. This error was NOT reproducible when running a node on betanet.
Commands tested include:
`goal wallet new`
`goal account new`
`goal account list`

`─[1] <> ./goal wallet new priv-beta-wallet1 -d ~/priv-betanet
Please choose a password for wallet 'priv-beta-wallet1':
Please confirm the password:
Creating wallet...
Created wallet 'priv-beta-wallet1'
Your new wallet has a backup phrase that can be used for recovery.
Keeping this backup phrase safe is extremely important.
Would you like to see it now? (Y/n): n
ERRO[0012] [Stack] goroutine 1 [running]:
runtime/debug.Stack(0xc000202050, 0xc000132010, 0xc00022e5f0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/debug/stack.go:24 +0x9d
github.com/algorand/go-algorand/logging.logger.Error(0xc000202050, 0xc000132010, 0xc00009a5b0, 0x1, 0x1)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/logging/log.go:223 +0x48
main.(*AccountsList).dumpList(0xc0001fac00)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/accountsList.go:189 +0x1a6
main.(*AccountsList).setDefaultWalletID(...)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/accountsList.go:82
main.glob..func78(0x574baa0, 0xc0002b4b70, 0x1, 0x3)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/wallet.go:183 +0x7e9
github.com/spf13/cobra.(*Command).execute(0x574baa0, 0xc0002b4ae0, 0x3, 0x3, 0x574baa0, 0xc0002b4ae0)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x5745e00, 0x4d5ed4b, 0x7, 0x4d5ab7e)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/commands.go:148 +0x97
  file=accountsList.go function="main.(*AccountsList).dumpList" line=189
ERRO[0012] open /Users/sam/priv-betanet/priv-betanet-v1/accountList.json: no such file or directory  file=accountsList.go function="main.(*AccountsList).dumpList" line=189
open /Users/sam/priv-betanet/priv-betanet-v1/accountList.json: no such file or directory%
`

`└─[0] <> ./goal account new -d ~/priv-betanet -w priv-beta-wallet1
Please enter the password for wallet 'priv-beta-wallet1':
ERRO[0002] [Stack] goroutine 1 [running]:
runtime/debug.Stack(0xc0001485a0, 0xc000130080, 0xc0000de9b0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/debug/stack.go:24 +0x9d
github.com/algorand/go-algorand/logging.logger.Error(0xc0001485a0, 0xc000130080, 0xc0002e0d70, 0x1, 0x1)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/logging/log.go:223 +0x48
main.(*AccountsList).dumpList(0xc0000b1e80)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/accountsList.go:189 +0x1a6
main.(*AccountsList).addAccount(0xc0000b1e80, 0xc00013a050, 0x9, 0xc000156700, 0x3a)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/accountsList.go:150 +0xe0
main.glob..func4(0x574c680, 0xc0000b1e40, 0x0, 0x4)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/account.go:313 +0x380
github.com/spf13/cobra.(*Command).execute(0x574c680, 0xc0000b1dc0, 0x4, 0x4, 0x574c680, 0xc0000b1dc0)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x5745e00, 0x4d5ed4b, 0x7, 0x4d5ab7e)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/commands.go:148 +0x97
  file=accountsList.go function="main.(*AccountsList).dumpList" line=189
ERRO[0002] open /Users/sam/priv-betanet/priv-betanet-v1/accountList.json: no such file or directory  file=accountsList.go function="main.(*AccountsList).dumpList" line=189
open /Users/sam/priv-betanet/priv-betanet-v1/accountList.json: no such file or directoryCreated new account with address UICXNMSVHYQACZWDGBGSJQLT4RXMN4CQQCBNCNIBWAGLZRMKUUYPS7VSWM`

`└─[0] <> ./goal account list -d ~/priv-betanet
ERRO[0000] [Stack] goroutine 1 [running]:
runtime/debug.Stack(0xc0000be320, 0xc0000ba478, 0xc000282280)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/debug/stack.go:24 +0x9d
github.com/algorand/go-algorand/logging.logger.Error(0xc0000be320, 0xc0000ba478, 0xc0001421a0, 0x1, 0x1)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/logging/log.go:223 +0x48
main.(*AccountsList).dumpList(0xc0000e7600)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/accountsList.go:189 +0x1a6
main.(*AccountsList).setDefaultWalletID(...)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/accountsList.go:82
main.getWalletHandleMaybePassword(0x7ffeefbff947, 0x17, 0x0, 0x0, 0xc00025a600, 0xc000239638, 0x491d43e, 0xc00030a000, 0x38, 0x0, ...)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/commands.go:406 +0xfb8
main.ensureWalletHandleMaybePassword(0x7ffeefbff947, 0x17, 0x0, 0x0, 0x0, 0x100000000000028, 0x400dc49, 0x8, 0x400dc49, 0x2108421084, ...)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/commands.go:378 +0x73
main.ensureWalletHandle(...)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/commands.go:373
main.glob..func9(0x574d260, 0xc0000a96a0, 0x0, 0x2)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/account.go:440 +0xf9
github.com/spf13/cobra.(*Command).execute(0x574d260, 0xc0000a9640, 0x2, 0x2, 0x574d260, 0xc0000a9640)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x5745e00, 0x4d5ed4b, 0x7, 0x4d5ab7e)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/commands.go:148 +0x97
  file=accountsList.go function="main.(*AccountsList).dumpList" line=189
ERRO[0000] open /Users/sam/priv-betanet/priv-betanet-v1/accountList.json: no such file or directory  file=accountsList.go function="main.(*AccountsList).dumpList" line=189
open /Users/sam/priv-betanet/priv-betanet-v1/accountList.json: no such file or directory[n/a]	UICXNMSVHYQACZWDGBGSJQLT4RXMN4CQQCBNCNIBWAGLZRMKUUYPS7VSWM	UICXNMSVHYQACZWDGBGSJQLT4RXMN4CQQCBNCNIBWAGLZRMKUUYPS7VSWM	[n/a] microAlgos`

**Comment by wisthsb1519** [comment]
running the updater fixes this `./update.sh -i -c beta -p . -d ~/priv-betanet -n`
