### ISSUE TITLE
Sporadic travis test failure: TestWebsocketNetworkNoAddress

### ISSUE THREAD

**Issue by Vervious** [algorand/go-algorand#74]
```
--- FAIL: TestWebsocketNetworkNoAddress (2.05s)
    testingLogger.go:38: time="2019-06-21T12:32:16.621797 +0000" level=warning msg="Reducing IncomingConnectionsLimit from 9223372036854775807 to 29744 since RLIMIT_NOFILE is 30000" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).rlimitIncomingConnections" line=580
    testingLogger.go:38: time="2019-06-21T12:32:16.623022 +0000" level=debug msg="listening on 127.0.0.1:33597" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).Start" line=621
    testingLogger.go:38: time="2019-06-21T12:32:16.633365 +0000" level=info msg="serving genesisID=\"go-test-network-genesis\" on \"http://127.0.0.1:33597\"" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).Start" line=651
    wsNetwork_test.go:286: http://127.0.0.1:33597
    testingLogger.go:38: time="2019-06-21T12:32:16.634857 +0000" level=warning msg="Reducing IncomingConnectionsLimit from 9223372036854775807 to 29744 since RLIMIT_NOFILE is 30000" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).rlimitIncomingConnections" line=580
    testingLogger.go:38: time="2019-06-21T12:32:16.638415 +0000" level=debug msg="no dns lookup due to empty bootstrapID" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).readFromBootstrap" line=1322
    testingLogger.go:38: time="2019-06-21T12:32:16.638665 +0000" level=debug msg="got no DNS addrs for network \"devtestnet\"" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).meshThread" line=1169
    testingLogger.go:38: time="2019-06-21T12:32:16.651376 +0000" level=debug msg="no dns lookup due to empty bootstrapID" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).readFromBootstrap" line=1322
    testingLogger.go:38: time="2019-06-21T12:32:16.651677 +0000" level=debug msg="got no DNS addrs for network \"devtestnet\"" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).meshThread" line=1169
    testingLogger.go:38: time="2019-06-21T12:32:16.654467 +0000" level=info msg="serving genesisID=\"go-test-network-genesis\" on \"http:\"" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).Start" line=651
    testingLogger.go:38: time="2019-06-21T12:32:16.662641 +0000" level=debug msg="inbound from 127.0.0.1:60308" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).ServeHTTP" line=842
    testingLogger.go:38: time="2019-06-21T12:32:16.663280 +0000" level=debug msg="wsPeer init outgoing=false \"http:\"" file=wsPeer.go function="github.com/algorand/go-algorand/network.(*wsPeer).init" line=210
    testingLogger.go:38: time="2019-06-21T12:32:16.666723 +0000" level=debug msg="wsPeer init outgoing=true \"http://127.0.0.1:33597\"" file=wsPeer.go function="github.com/algorand/go-algorand/network.(*wsPeer).init" line=210
    testingLogger.go:38: time="2019-06-21T12:32:16.668757 +0000" level=debug msg=ready file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).addPeer" line=1614
    testingLogger.go:38: time="2019-06-21T12:32:16.668985 +0000" level=info msg="Made outgoing connection to peer http://127.0.0.1:33597" event=ConnectedOut file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).tryConnect" line=1499 local="http:" remote="http://127.0.0.1:33597"
    testingLogger.go:38: time="2019-06-21T12:32:16.670500 +0000" level=debug msg=ready file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).addPeer" line=1614
    testingLogger.go:38: time="2019-06-21T12:32:16.670729 +0000" level=info msg="Accepted incoming connection from peer http:" event=ConnectedIn file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).ServeHTTP" line=878 local="http://127.0.0.1:33597" remote="http:"
    wsNetwork_test.go:296: a ready
    wsNetwork_test.go:298: b ready
    wsNetwork_test.go:306: timeout, count=0, wanted 2
    wsNetwork_test.go:289: stopping B
    testingLogger.go:38: time="2019-06-21T12:32:18.673230 +0000" level=debug msg="closed " file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).Stop" line=695
    wsNetwork_test.go:289: B done
    wsNetwork_test.go:278: stopping A
    testingLogger.go:38: time="2019-06-21T12:32:18.674990 +0000" level=debug msg="closed 127.0.0.1:33597" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).Stop" line=695
    wsNetwork_test.go:278: A done
time="2019-06-21T12:32:23.792356 +0000" level=error msg="[Stack] goroutine 57920 [running]:\nruntime/debug.Stack(0xc000394410, 0xc0000ae960, 0xc000394500)\n\t/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/debug/stack.go:24 +0xab\ngithub.com/algorand/go-algorand/logging.logger.Errorf(0xc000394410, 0xc0000ae960, 0x118b4f6, 0x24, 0xc0018e4a80, 0x2, 0x2)\n\t/home/travis/gopath/src/github.com/algorand/go-algorand/logging/log.go:226 +0x56\ngithub.com/algorand/go-algorand/network.(*WebsocketNetwork).updateURLHost(0xc0003ddae0, 0x11967c6, 0x3e, 0xc000419ac0, 0x10, 0x10, 0xc00039a1e8, 0x1, 0x44, 0x3f0976265587cf75)\n\t/home/travis/gopath/src/github.com/algorand/go-algorand/network/wsNetwork.go:785 +0x1ce\ngithub.com/algorand/go-algorand/network.TestWebsocketNetwork_updateUrlHost.func1(0xc000115500)\n\t/home/travis/gopath/src/github.com/algorand/go-algorand/network/wsNetwork_test.go:1169 +0x192\ntesting.tRunner(0xc000115500, 0xc007f3edd0)\n\t/home/travis/.gimme/versions/go1.12.linux.amd64/src/testing/testing.go:865 +0x164\ncreated by testing.(*T).Run\n\t/home/travis/.gimme/versions/go1.12.linux.amd64/src/testing/testing.go:916 +0x69a\n" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).updateURLHost" line=785
time="2019-06-21T12:32:23.793027 +0000" level=error msg="unable to parse url: 'http://[2601:192:4b40:6a23:2999:acf5:c0f6:47dc]:80:aaa/bbb/ccc', error: parse http://[2601:192:4b40:6a23:2999:acf5:c0f6:47dc]:80:aaa/bbb/ccc: invalid port \":80:aaa\" after host" file=wsNetwork.go function="github.com/algorand/go-algorand/network.(*WebsocketNetwork).updateURLHost" line=785
FAIL
FAIL	github.com/algorand/go-algorand/network	32.185s
Makefile:194: recipe for target 'short_test_target_github.com/algorand/go-algorand/network' failed
make: *** [short_test_target_github.com/algorand/go-algorand/network] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by Vervious** [comment]
[travis.log](https://github.com/algorand/go-algorand/files/3315263/travis.log)

**Comment by tsachiherman** [comment]
I have already fixed this issue : 
https://github.com/algorand/go-algorand/pull/75
Please let me know if you still see this issue.
